Repository IUT-Blagnac/sae3-01-devapp-g2a-8, pull requests merged in 2022-12, with the labels that each got.

#16 appli iot fonctionnelle #9
  IoT/Python/appli.py
  IoT/Python/config.json
Labels: IoT

#30 ajout du site web #15
  Site/css/style.css
  Site/index.html
  Site/logos/compte.png
  Site/logos/logo.png
  Site/logos/menu.png
Labels: web

#32 partie connexion terminée #23
  Site/compte.php
  Site/formConnexion.php
  Site/formContact.php
  Site/formCreation.php
  Site/include/connect.inc.php
  Site/include/css/style.css
  Site/include/footer.php
  Site/include/header.php
  Site/include/logos/compte.png
  Site/include/logos/logo.png
  Site/include/logos/menu.png
  Site/include/menu.php
  Site/index.html
  Site/index.php
  Site/traitConnexion.php
  Site/traitContact.php
  Site/traitCreation.php
Labels: web

#54 Script de création de la BD et insert #17
  BD/insert_BD.sql
  BD/script_BD.sql
  Documentation/images/DCBD.png
Labels: BD, vérifié

#56 fix bug oubli des droits #55
  IoT/Python/appli.py
Labels: IoT, vérifié

#57 mise à jour de la doc user iot #31
  Documentation/Doc_utilisateur_iot.adoc
Labels: documentation, IoT

#60 #27 partie site terminée pour ce sprint
  Site/compte.php
  Site/deconnexion.php
  Site/formConnexion.php
  Site/formContact.php
  Site/formCreation.php
  Site/include/css/style.css
  Site/include/footer.php
  Site/include/header.php
  Site/include/icon.php
  Site/include/logos/favicon.ico
  Site/include/menu.php
  Site/index.php
  Site/modificationCompte.php
  Site/modificationMdp.php
  Site/suppressionCompte.php
  Site/traitConnexion.php
  Site/traitCreation.php
  Site/traitModificationCompte.php
  Site/traitModificationMdp.php
Labels: web

#61 #59 bug bd conception
  BD/insert_BD.sql
  BD/script_BD.sql
  Documentation/G2A08_ConceptionBD_v2.pdf
Labels: BD
